name: flutter_ui_practice
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-54.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  fonts:
    - family: GoodTimesRg
      fonts:
        - asset: assets/fonts/good_times.otf
